# Extending core lint rules
include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.7.0.0.yaml
  - package:lint/analysis_options.yaml


analyzer:
  exclude:
    # Generated files
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
    - "**/*.config.dart"
    - "**/*.chopper.dart"
    - "**/*.graphql.dart"
    - "**/*.gql.dart"
    - "**/*.module.dart"
    - "lib/generated/**"
    - "lib/**.gen.dart"
    - "lib/generated_plugin_registrant.dart"
    # Test files
    - "test/**.mocks.dart"
    - "**/test/generated_*.dart"
    # Build
    - "build/**"
    - ".dart_tool/**"
    # Assets
    - "assets/**"
    - "bricks/**"

  plugins:
    - custom_lint

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
    enable-experiment:
       - sealed-class
       - patterns
       - records
       - macros
       - extension-types

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Architecture & Design
    implementation_imports: error
    invalid_use_of_visible_for_testing_member: error
    public_member_api_docs: error
    avoid_relative_lib_imports: error
    directives_ordering: error
    depend_on_referenced_packages: error
    package_api_docs: error
    library_private_types_in_public_api: error
    invalid_dependency: error
    missing_dependency: error
    cyclomatic_complexity: error
    number_of_parameters: error
    max_nesting: error
    lines_of_code: error
    maintainability_index: error
    max_methods: error
    class_weight: error
    # Critical Errors
    todo: error
    dead_code: error
    invalid_annotation_target: error
    missing_enum_constant_in_switch: error
    missing_required_param: error
    must_call_super: error
    await_only_futures: error
    empty_catches: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    undefined_hidden_name: error
    undefined_shown_name: error
    unreachable_from_main: error
    unsafe_html: error
    unused_element: error
    unused_field: error
    unused_import: error
    unused_local_variable: error
    unused_shown_name: error

    # Type Safety
    always_specify_types: error
    strict_raw_type: error
    invalid_assignment: error
    return_of_invalid_type: error
    argument_type_not_assignable: error
    unchecked_use_of_nullable_value: error
    null_check_on_nullable_type_parameter: error
    nullable_type_in_catch_clause: error
    invalid_null_aware_operator: error

    # Code Style & Maintainability
    avoid_annotating_with_dynamic: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_field_initializers_in_const_classes: error
    avoid_final_parameters: error
    avoid_implementing_value_types: error
    avoid_js_rounded_ints: error
    avoid_returning_null: error
    avoid_returning_null_for_future: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_slow_async_io: error
    avoid_type_to_string: error
    avoid_types_as_parameter_names: error
    avoid_web_libraries_in_flutter: error
    collection_methods_unrelated_type: error
    comment_references: error
    diagnostic_describe_all_properties: error
    do_not_use_environment: error
    exhaustive_cases: error
    file_names: error
    flutter_style_todos: error
    implicit_reopen: error
    invalid_case_patterns: error
    lines_longer_than_80_chars: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: error
    no_logic_in_create_state: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    sized_box_shrink_expand: error
    type_annotate_public_apis: error
    unawaited_futures: error
    use_build_context_synchronously: error
    use_decorated_box: error
    use_key_in_widget_constructors: error
    use_named_constants: error
    use_setters_to_change_properties: error
    use_string_buffers: error
    void_checks: error

    # Documentation
    missing_code_block_language_in_doc_comment: error
    missing_whitespace_between_adjacent_strings: error
    package_prefixed_library_names: error
    slash_for_doc_comments: error

    always_put_control_body_on_new_line: error
    always_specify_parameter_types: error
    avoid_as: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_function_literals_in_foreach_calls: error
    avoid_private_typedef_functions: error
    avoid_redundant_argument_values: error
    avoid_returning_null_for_void: error
    avoid_single_cascade_in_expression_statements: error
    avoid_types_on_closure_parameters: error
    cascade_invocations: error
    cast_nullable_to_non_nullable: error
    combinators_ordering: error
    conditional_uri_does_not_exist: error
    deprecated_member_use_from_same_package: error
    discarded_futures: error
    invalid_visibility_annotation: error
    no_runtimeType_toString: error
    noop_primitive_operations: error
    prefer_expression_function_bodies: error
    prefer_final_parameters: error
    prefer_foreach: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_int_literals: error
    prefer_mixin: error
    prefer_null_aware_method_calls: error
    secure_pubspec_urls: error
    sort_unnamed_constructors_first: error
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_await_in_return: error
    unnecessary_lambdas: error
    unnecessary_null_aware_assignments: error
    unnecessary_parenthesis: error
    unnecessary_raw_strings: error
    unnecessary_statements: error
    use_if_null_to_convert_nulls_to_bools: error
    use_is_even_rather_than_modulo: error
    use_raw_strings: error
    valid_regexps: error


linter:
  rules:
    - cyclomatic_complexity: 10
    - number_of_parameters: 1
    - max_nesting: 4
    - lines_of_code: 50
    - maintainability_index: 50
    - max_methods: 10
    - class_weight: 0.33
    - max_lines_for_file: 250  # Total file length constraint
    - always_declare_return_types : true
    - always_put_required_named_parameters_first : true
    - always_specify_types  : true
    - always_use_package_imports: true
    - avoid_implementing_value_types: true
    - avoid_relative_lib_imports: true
    - avoid_return_types_on_setters: true
    - avoid_returning_this: true
    - avoid_setters_without_getters: true
    - avoid_unused_constructor_parameters: true
    - avoid_void_async: true
    - cascade_invocations: true
    - directives_ordering: true
    - do_not_use_environment: true
    - exhaustive_cases: true
    - library_private_types_in_public_api: true
    - no_default_cases: true
    - package_api_docs: true
    - prefer_final_fields: true
    - prefer_final_in_for_each: true
    - prefer_final_locals: true
    - prefer_interpolation_to_compose_strings : true
    - public_member_api_docs: true
    - sort_constructors_first: true
    - type_annotate_public_apis: true
    - unnecessary_getters_setters: true
    - use_setters_to_change_properties : true

    # Flutter specific
    - sized_box_for_whitespace : true
    - sized_box_shrink_expand : true
    - sort_child_properties_last: true
    - use_build_context_synchronously: true
    - use_colored_box: true
    - use_decorated_box: true
    - use_full_hex_values_for_flutter_colors: true
    - use_key_in_widget_constructors: true
    - use_super_parameters: true

    # Code quality
    - annotate_overrides : true
    - annotate_redeclares: true
    - avoid_bool_literals_in_conditional_expressions: true
    - avoid_catching_errors: true
    - avoid_double_and_int_checks: true
    - avoid_dynamic_calls: true
    - avoid_empty_else: true
    - avoid_equals_and_hash_code_on_mutable_classes: true
    - avoid_escaping_inner_quotes: true
    - avoid_field_initializers_in_const_classes: true
    - avoid_function_literals_in_foreach_calls: true
    - avoid_init_to_null: true
    - avoid_multiple_declarations_per_line: true
    - avoid_null_checks_in_equality_operators: true
    - avoid_positional_boolean_parameters: true
    - avoid_print: true
    - avoid_redundant_argument_values: true
    - avoid_renaming_method_parameters: true
    - avoid_returning_null_for_void: true
    - avoid_shadowing_type_parameters: true
    - avoid_single_cascade_in_expression_statements: true
    - avoid_slow_async_io: true
    - avoid_type_to_string: true
    - avoid_types_as_parameter_names: true
    - avoid_unnecessary_containers: true
    - await_only_futures: true
    - camel_case_extensions : true
    - camel_case_types: true
    - cancel_subscriptions: true
    - cast_nullable_to_non_nullable: true
    - collection_methods_unrelated_type: true
    - combinators_ordering: true
    - comment_references: true
    - constant_identifier_names: true
    - control_flow_in_finally: true
    - curly_braces_in_flow_control_structures: true
    - dangling_library_doc_comments: true
    - depend_on_referenced_packages: true
    - deprecated_consistency: true
    - empty_catches: true
    - empty_constructor_bodies: true
    - empty_statements: true
    - eol_at_end_of_file: true
    - file_names: true
    - hash_and_equals: true
    - implicit_call_tearoffs: true
    - invalid_case_patterns: true
    - join_return_with_assignment: true
    - leading_newlines_in_multiline_strings: true
    - library_annotations: true
    - library_names: true
    - library_prefixes: true
    - lines_longer_than_80_chars: true
    - literal_only_boolean_expressions: true
    - missing_whitespace_between_adjacent_strings: true
    - no_adjacent_strings_in_list: true
    - no_duplicate_case_values: true
    - no_leading_underscores_for_library_prefixes: true
    - no_leading_underscores_for_local_identifiers: true
    - no_literal_bool_comparisons: true
    - no_runtimeType_toString: true
    - null_check_on_nullable_type_parameter: true
    - null_closures: true
    - one_member_abstracts: true
    - only_throw_errors: true
    - overridden_fields: true
    - package_names: true
    - parameter_assignments: true
    - prefer_adjacent_string_concatenation: true
    - prefer_asserts_in_initializer_lists: true
    - prefer_asserts_with_message: true
    - prefer_collection_literals: true
    - prefer_conditional_assignment: true
    - prefer_const_constructors: true
    - prefer_const_constructors_in_immutables: true
    - prefer_const_declarations: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_constructors_over_static_methods: true
    - prefer_contains: true
    - prefer_expression_function_bodies: true
    - prefer_for_elements_to_map_fromIterable: true
    - prefer_foreach: true
    - prefer_function_declarations_over_variables: true
    - prefer_generic_function_type_aliases: true
    - prefer_if_elements_to_conditional_expressions: true
    - prefer_if_null_operators: true
    - prefer_initializing_formals: true
    - prefer_inlined_adds: true
    - prefer_int_literals: true
    - prefer_is_empty: true
    - prefer_is_not_empty: true
    - prefer_is_not_operator: true
    - prefer_iterable_whereType: true
    - prefer_mixin: true
    - prefer_null_aware_method_calls: true
    - prefer_null_aware_operators: true
    - prefer_single_quotes: true
    - prefer_spread_collections: true
    - prefer_typing_uninitialized_variables: true
    - prefer_void_to_null: true
    - provide_deprecation_message: true
    - recursive_getters: true
    - require_trailing_commas: true
    - slash_for_doc_comments: true
    - sort_pub_dependencies: true
    - sort_unnamed_constructors_first: true
    - test_types_in_equals: true
    - throw_in_finally: true
    - tighten_type_of_initializing_formals: true
    - type_init_formals: true
    - type_literal_in_constant_pattern: true
    - unawaited_futures: true
    - unnecessary_await_in_return: true
    - unnecessary_brace_in_string_interps: true
    - unnecessary_breaks: true
    - unnecessary_const: true
    - unnecessary_constructor_name: true
    - unnecessary_late: true
    - unnecessary_library_directive: true
    - unnecessary_new: true
    - unnecessary_null_aware_assignments: true
    - unnecessary_null_aware_operator_on_extension_on_nullable: true
    - unnecessary_null_checks: true
    - unnecessary_null_in_if_null_operators: true
    - unnecessary_nullable_for_final_variable_declarations: true
    - unnecessary_overrides: true
    - unnecessary_parenthesis: true
    - unnecessary_raw_strings: true
    - unnecessary_statements: true
    - unnecessary_string_escapes: true
    - unnecessary_string_interpolations: true
    - unnecessary_this: true
    - unnecessary_to_list_in_spreads: true
    - unreachable_from_main: true
    - unrelated_type_equality_checks: true
    - use_enums: true
    - use_function_type_syntax_for_parameters: true
    - use_if_null_to_convert_nulls_to_bools: true
    - use_is_even_rather_than_modulo: true
    - use_late_for_private_fields_and_variables: true
    - use_named_constants: true
    - use_raw_strings: true
    - use_rethrow_when_possible: true
    - use_string_buffers: true
    - use_test_throws_matchers: true
    - valid_regexps: true
    - always_put_control_body_on_new_line: true
    - avoid_private_typedef_functions: true
    - conditional_uri_does_not_exist: true
    - deprecated_member_use_from_same_package: true
    - discarded_futures: true
    - implicit_reopen: true
    - prefer_final_parameters: true
    - secure_pubspec_urls: true
    - unnecessary_lambdas: true
    - use_to_and_as_if_applicable: true

custom_lint:
  rules:
    # Clean Architecture enforcements
    - avoid_layer_violation: true
    - avoid_data_layer_in_presentation: true
    - avoid_domain_layer_in_presentation: true
    - avoid_infrastructure_layer_in_domain: true
    - avoid_data_layer_in_domain: true
    - enforce_dependency_direction: true
    - proper_repository_usage: true
    - proper_use_case_usage: true
    - entities_must_be_immutable: true
    - avoid_business_logic_in_presentation: true
    - value_objects_must_be_validated: true
    - enforce_exception_handling: true
    - enforce_failure_handling: true
    - use_case_single_responsibility: true
    - repository_single_responsibility: true
    - force_provider_annotation: true
    - prefer_sealed_classes: true
    - require_property_documentation: true
    - must_be_immutable: true
    - avoid_passing_async_when_sync_expected: true
    - avoid_dynamic: true
    - avoid_returning_widgets: true
    - prefer_async_await: true
    - prefer_correct_edge_insets_constructor: true
    - prefer_single_widget_per_file: true
    - no-empty-static-constructor: true
    - avoid_cascading_async_calls: true
    - avoid_hardcoded_colors: true
    - avoid_global_state: true
    - force_declare_api_class: true
    - force_riverpod_hooks_usage: true
    - prefer-match-file-name: true
    - prefer-static-class: true
    - member-ordering-extended: true
    - prefer-correct-identifier-length:
        min-identifier-length: 3
        max-identifier-length: 30
    - prefer-correct-type-name:
        min-length: 3
        max-length: 40
    - prefer-match-file-name: true
    - no-equal-then-else: true
    - prefer-first: true
    - prefer-last: true
    - no-boolean-literal-compare: true
    - prefer-conditional-expressions: true
    - no-empty-block: true
    - no-magic-number: true
    - prefer-trailing-comma: true
    - prefer-unique-entity-names: true

    # Performance
    - binary-expression-operand-order: true
    - double-literal-format: true
    - no-equal-arguments: true
    - avoid-mutating-parameters: true
    - avoid-unnecessary-setstate: true
    - prefer-async-await: true
    - prefer-correct-edge-insets-constructor: true
    - avoid-unnecessary-type-assertions: true
    - avoid-unnecessary-type-casts: true
    - prefer-extracting-callbacks: true

    # Style
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-redundant-else: true
    - avoid-late-keyword: true
    - avoid-unused-parameters: true
    - avoid-duplicate-exports: true
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-commenting-analyzer-ignores: true
    - no-empty-block: true
    - newline-before-return: true
    - prefer-immediate-return: true