name: todo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  pillu_app:
    git:
      url: https://github.com/Scaibu/pillu_app.git
      ref: main
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0

  # performance optimizations
  get_it: ^8.0.3
  equatable: ^2.0.5

  nb_utils: ^7.1.3
  fpdart: ^1.1.1
  go_router: ^14.8.1
  flutter_hooks: ^0.20.5
  http: ^1.2.1

  # for localization
  easy_localization: ^3.0.7+1

  # firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_crashlytics: ^4.3.4

  hive: ^2.2.3
  path_provider: ^2.1.5
  mix: ^1.5.4
  nested: ^1.0.0
  provider: ^6.1.4
  firebase_auth: ^5.5.1


  # Code generator
  envied: ^1.1.1
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  onesignal_flutter: ^5.3.0

  clean_architecture_with_state_management: ^1.2.0
  firebase_analytics: ^11.4.4
  flutter_svg: ^2.0.17
  tuple: ^2.0.2
  #  flutter pub run clean_architecture_with_state_management chat -bloc
  mockito: ^5.4.5
  analyzer: ^7.3.0
  rxdart: ^0.28.0
  collection: ^1.18.0
  async: ^2.12.0
  bloc_test: ^10.0.0
  flex_color_picker: ^3.7.0
  percent_indicator: ^4.2.4
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  google_sign_in: ^6.3.0
  cached_network_image: ^3.4.1
  google_fonts: ^4.0.5 # TODO UPDATE THIS TO : google_fonts: ^6.2.1
  path: ^1.9.1
  custom_lint_builder: ^0.7.5
  scaibu_mutex_lock: ^1.0.6

dependency_overrides:
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter test --coverage --reporter=expanded /home/j/live/scaibutodoapp/test/tags_tests.dart
  # This will execute the test cases defined in the tags_tests.dart file.

  custom_lints:
    path: custom_lints/custom_lints
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  lint: ^2.8.0
  dart_code_metrics_presets: ^2.21.0
#  dart analyze lib/feature/auth/data/repository/auth_repository_impl.dart
#  use this for analysis


# main command =>  flutter pub run build_runner build --delete-conflicting-outputs

#  Commands
# 1. build: Runs a single build and exits.
# 2. watch: Runs a persistent build server that watches the files system for edits and does rebuilds as necessary.
# 3. serve: Same as watch, but runs a development server as well.
# 4. test: Runs a single build, creates a merged output directory, and then runs dart run test --precompiled <merged-output-dir>. See below for instructions on passing custom args to the test command.

#  Command Line Options
# All the above commands support the following arguments:
# 1. --help: Print usage information for the command.
# 2. --delete-conflicting-outputs: Assume conflicting outputs in the users package are from previous builds, and skip the user prompt that would usually be provided.
# 3. --[no-]fail-on-severe: Whether to consider the build a failure on an error logged. By default this is false.
# 4. --build-filter: Build filters allow you to choose explicitly which files to build instead of building entire directories. See further documentation on this feature here.


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/image/
    - assets/icon/
    - assets/json/loginPageAssets/
    - pillu_assets/
    - pillu_assets/3.0x/
    - pillu_assets/2.0x/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
