name: todo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # performance optimizations
  get_it: ^8.0.0-pre-5
  equatable: ^2.0.5

  nb_utils: ^7.0.3
  fpdart: ^1.1.0
  go_router: ^14.2.0
  flutter_hooks: ^0.20.5
  http: ^1.2.1

  # for localization
  easy_localization: ^3.0.7

  # firebase
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_crashlytics: ^4.0.1

  hive: ^2.2.3
  path_provider: ^2.1.3
  internet_connection_checker_plus: ^2.4.2
  mix: ^1.0.0
  nested: ^1.0.0
  provider: ^6.1.2
  firebase_auth: ^5.1.1
  lottie: ^3.1.2


  # Code generator
  envied: ^0.5.4+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  onesignal_flutter: ^5.2.1

  clean_architecture_with_state_management: ^1.1.2
  firebase_analytics: ^11.2.1
  flutter_svg: ^2.0.10+1
  tuple: ^2.0.2
  #  flutter pub run clean_architecture_with_state_management chat -bloc
  mockito: ^5.4.4

dependency_overrides:
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

# main command =>  flutter pub run build_runner build --delete-conflicting-outputs

#  Commands
# 1. build: Runs a single build and exits.
# 2. watch: Runs a persistent build server that watches the files system for edits and does rebuilds as necessary.
# 3. serve: Same as watch, but runs a development server as well.
# 4. test: Runs a single build, creates a merged output directory, and then runs dart run test --precompiled <merged-output-dir>. See below for instructions on passing custom args to the test command.

#  Command Line Options
# All the above commands support the following arguments:
# 1. --help: Print usage information for the command.
# 2. --delete-conflicting-outputs: Assume conflicting outputs in the users package are from previous builds, and skip the user prompt that would usually be provided.
# 3. --[no-]fail-on-severe: Whether to consider the build a failure on an error logged. By default this is false.
# 4. --build-filter: Build filters allow you to choose explicitly which files to build instead of building entire directories. See further documentation on this feature here.


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/image/
    - assets/icon/
    - assets/json/loginPageAssets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
